config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/new', to: 'games#new'
  post '/score', to: 'games#score'
  get '/reset', to: 'games#reset'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
require 'json'
require 'open-uri'

class GamesController < ApplicationController
    def new
        @letters = []
        10.times do
            @letters << ('A'..'Z').to_a.sample
        end
        cookies[:score] = 0 if cookies[:score].nil?

        @score = cookies[:score]
    end

    def score
        @letters = params[:letters]
        @word = params[:word]
        
        if !letter_check?(@letters, @word)
            @scenario = 1;
        elsif !valid_check?(@word)
            @scenario = 2;
        else
            @scenario = 3;
            cookies[:score] = cookies[:score].to_i + @word.length**2
        end
        @score = cookies[:score]
    end

    def reset
        cookies[:score] = 0
        redirect_to new_path
    end
    
    private
    
    def letter_check?(letters, word)
        l_hash = {}
        w_hash = {}
        letters.downcase.chars.each {|l| l_hash[l] ? l_hash[l] += 1 : l_hash[l] = 1}
        word.downcase.chars.each {|l| w_hash[l] ? w_hash[l] += 1 : w_hash[l] = 1}

        return w_hash.all? {|k, v| l_hash[k] && l_hash[k] >= v}
    end
    
    def valid_check?(word)
        url = "https://wagon-dictionary.herokuapp.com/#{@word}"
    
        result_serialized = open(url).read
        result = JSON.parse(result_serialized)
    
        return result["found"]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/new.html.erb
<h1>New game</h1>
<p>Score = <%= @score %></p>

<ul>
    <% @letters.each do |l| %>
        <li><%= l %></li>
    <% end %>
</ul>
<p>What is the longest word you can find?</p>
<form action="/score" method="post">
    <input type="text" name="word">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <%= hidden_field_tag "letters", @letters.join %>
    <input type="submit">
</form>

<%= link_to 'Reset', reset_path %>

app/views/games/score.html.erb
<h1>Result</h1>
<p>Score = <%= @score %></p>

<p>
    <% if @scenario == 1 %>
        Sorry but <strong><%= @word.upcase %></strong> can't be built out of <%= @letters.chars.join(', ') %>    
    <% elsif @scenario == 2 %>
        Sorry but <strong><%= @word.upcase %></strong> does not seem to be a valid English word...
    <% else %>
        <strong>Congratulations!</strong> <%= @word.upcase %> is a valid English word!
    <% end %>
</p>

<%= link_to "Play again", new_path %>

<%= link_to 'Reset', reset_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LW438RailsLwordGame</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>